version: "3"
services:
    quiz_session_db:
        image: postgres:13.5
        container_name: quiz-session-db
        restart: always
        environment:
            - POSTGRES_USER=richardktran
            - POSTGRES_PASSWORD=password
        volumes:
            - ./postgres_db:/var/lib/postgresql/data
        ports:
            - '5433:5432'

volumes:
    postgres_db:
        driver: local