INSERT INTO questions (id, question, options, correct_answer, time_limit) VALUES
('q-1', 'What is the chemical symbol for gold?', '["Au", "Ag", "Fe", "Cu"]', 0, 15),
('q-2', 'Which planet is known as the Red Planet?', '["Venus", "Mars", "Jupiter", "Saturn"]', 1, 15),
('q-3', 'What is the powerhouse of the cell?', '["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"]', 2, 15),
('q-4', 'How many bones are in the adult human body?', '["186", "206", "226", "256"]', 1, 15),
('q-5', 'What gas do plants absorb from the atmosphere?', '["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"]', 2, 15),
('q-6', 'In which year did World War II end?', '["1943", "1944", "1945", "1946"]', 2, 15),
('q-7', 'Who was the first President of the United States?', '["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"]', 1, 15),
('q-8', 'The Great Wall of China was primarily built to protect against invasions from which direction?', '["South", "West", "North", "East"]', 2, 15),
('q-9', 'Which ancient civilization built the pyramids at Giza?', '["Romans", "Greeks", "Egyptians", "Persians"]', 2, 15),
('q-10', 'Who wrote the Declaration of Independence?', '["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"]', 1, 15),
('q-11', 'What is the capital of Australia?', '["Sydney", "Melbourne", "Canberra", "Perth"]', 2, 15),
('q-12', 'Which is the longest river in the world?', '["Amazon", "Nile", "Yangtze", "Mississippi"]', 1, 15),
('q-13', 'Mount Everest is located in which mountain range?', '["Alps", "Andes", "Himalayas", "Rockies"]', 2, 15),
('q-14', 'What is the smallest country in the world by area?', '["Monaco", "Vatican City", "San Marino", "Liechtenstein"]', 1, 15),
('q-15', 'Which ocean is the largest?', '["Atlantic", "Indian", "Arctic", "Pacific"]', 3, 15),
('q-16', 'How many players are on a standard soccer team on the field?', '["9", "10", "11", "12"]', 2, 15),
('q-17', 'In which sport would you perform a slam dunk?', '["Volleyball", "Basketball", "Tennis", "Baseball"]', 1, 15),
('q-18', 'Which country has won the most FIFA World Cup titles?', '["Germany", "Italy", "Brazil", "Argentina"]', 2, 15),
('q-19', 'How many rings are on the Olympic flag?', '["4", "5", "6", "7"]', 1, 15),
('q-20', 'In tennis, what is a score of zero called?', '["Nil", "Love", "Blank", "Zero"]', 1, 15),
('q-21', 'Who directed the movie "Jurassic Park"?', '["James Cameron", "Steven Spielberg", "George Lucas", "Ridley Scott"]', 1, 15),
('q-22', 'Which band released the album "Abbey Road"?', '["The Rolling Stones", "The Beatles", "Led Zeppelin", "Queen"]', 1, 15),
('q-23', 'What is the highest-grossing film of all time (unadjusted)?', '["Avengers: Endgame", "Avatar", "Titanic", "Star Wars: The Force Awakens"]', 1, 15),
('q-24', 'Which TV series features the character Walter White?', '["Breaking Bad", "The Sopranos", "Mad Men", "Better Call Saul"]', 0, 15),
('q-25', 'Who played Jack Dawson in the film "Titanic"?', '["Brad Pitt", "Leonardo DiCaprio", "Tom Cruise", "Johnny Depp"]', 1, 15);
